### ISSUE TITLE
Uncaught TypeError: j.whenReady is not a function

### ISSUE THREAD

**Issue by Bouni** [JezerM/lightdm-void-theme#1]
I use `web-greeter` and set the theme to `lightdm-void-theme` as described in the build & install section.
When the greeter is loaded I get an error saying "Uncaught TypeError: j.whenReady is not a function".

The `litarvan` theme installed from the AUR is the only one I could get to work ....

**Comment by JezerM** [comment]
Sorry for the late response.

This is a web-greeter bug, a considerable error. I will fix it soon.

**Comment by JezerM** [comment]
Fixed in https://github.com/JezerM/web-greeter/commit/6a4875ce83b4bc859cc9800dfc140fcc9ac46a2d.
